"""empty message

Revision ID: ce2bc8c4e0f3
Revises: 2a4dc1f53098
Create Date: 2020-12-26 17:10:16.549859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2bc8c4e0f3'
down_revision = '2a4dc1f53098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'subscribed')
    # ### end Alembic commands ###
